//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class AddClockViewController, WorldClockCity;

@protocol AddClockViewControllerDelegate
- (void)addClockViewController:(AddClockViewController *)arg1 addCity:(WorldClockCity *)arg2;
- (void)dismissAddViewController:(AddClockViewController *)arg1;
@end

