//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UISearchBarDelegate.h"

@class ClockSearchField, NSArray, NSMutableIndexSet, NSString, UILabel;

@interface AddClockViewController : UITableViewController <UISearchBarDelegate>
{
    ClockSearchField *_searchField;
    NSArray *_cities;
    NSArray *_partitionedCities;
    NSArray *_sectionIndexTitles;
    NSMutableIndexSet *_populatedIndexSet;
    id <AddClockViewControllerDelegate> _delegate;
    NSArray *_centerNoResultsFoundLabelConstraints;
    UILabel *_noResultsFoundLabel;
    struct CGRect _keyboardFrame;
}

- (void).cxx_destruct;
- (void)_addAutolayoutConstraintsForNoResultsFoundLabel;
- (double)_calculateVerticalMultiplierForKeyboard;
- (void)_dismiss;
- (void)_keyboardWillDismiss:(id)arg1;
- (void)_keyboardWillResize:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_reloadNoResultsFoundLabelForKeyboardNotification:(id)arg1;
- (void)_removeAutolayoutConstraintsForNoResultsFoundLabel;
- (void)_showNoResultsFound:(_Bool)arg1;
@property(retain, nonatomic) NSArray *centerNoResultsFoundLabelConstraints; // @synthesize centerNoResultsFoundLabelConstraints=_centerNoResultsFoundLabelConstraints;
@property(nonatomic) __weak id <AddClockViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(nonatomic) struct CGRect keyboardFrame; // @synthesize keyboardFrame=_keyboardFrame;
@property(retain, nonatomic) UILabel *noResultsFoundLabel; // @synthesize noResultsFoundLabel=_noResultsFoundLabel;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)prepopulateSuggestions;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
@property(readonly, nonatomic) ClockSearchField *searchField; // @synthesize searchField=_searchField;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

