//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TableViewController.h"

#import "AlarmActiveDelegate.h"
#import "AlarmDelegate.h"
#import "EditAlarmViewControllerDelegate.h"
#import "StateManagement.h"

@class Alarm, NSString, NSUserActivity;

@interface AlarmViewController : TableViewController <AlarmDelegate, AlarmActiveDelegate, EditAlarmViewControllerDelegate, StateManagement>
{
    _Bool _viewVisible;
    Alarm *_alarmToEdit;
    _Bool _didScrollToCurrentTime;
    NSUserActivity *_userActivity;
}

- (void).cxx_destruct;
- (id)_tableView:(id)arg1 templateLayoutCellForCellsWithReuseIdentifier:(id)arg2;
- (void)activeChangedForAlarm:(id)arg1 active:(_Bool)arg2;
- (id)addViewController;
- (void)alarmDidUpdate:(id)arg1;
- (id)contentScrollView;
- (void)didEditAlarm:(id)arg1;
- (void)dismissAddViewController:(id)arg1;
- (id)init;
- (void)loadView;
- (id)noItemsText;
- (long long)numberOfItems;
- (void)reloadState;
- (void)saveScrollPoint;
- (void)saveState;
- (void)showAddView;
- (void)showEditViewForRow:(long long)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

