//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "UIApplicationDelegate.h"

@class MobileTimerSecureWindow, MobileTimerTabBarController, NSString, NSTimer, UIViewController, UIWindow;

@interface AppController : UIApplication <UIApplicationDelegate>
{
    _Bool _initializationPerformed;
    NSTimer *_userPreferencesCommitTimer;
    MobileTimerSecureWindow *_window;
    MobileTimerTabBarController *_tabBarController;
    NSString *_currentTestName;
    long long _iterations;
}

- (void).cxx_destruct;
- (_Bool)_canShowTextServices;
- (void)_runRotationTest;
- (void)_runScrollTest:(id)arg1;
- (void)_selectViewController:(id)arg1;
- (void)_spinMainRunLoop;
- (void)_windowDidRotate:(id)arg1;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applyStyle;
- (void)cancelScheduledUserPreferencesCommit;
- (void)commitUserPreferences;
@property(readonly, nonatomic) __weak UIViewController *containerViewController;
- (id)copyInvalidAlarmsLog;
- (void)dealloc;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2;
- (void)handleFrameworkPreferencesNotification:(id)arg1;
- (void)handleLocalNotificationsChangedExternally;
- (void)handleLocalNotificationsChangedWithFullReload:(_Bool)arg1;
- (void)handleUserPreferencesChangedWithScheduledLocalNotificationsRefresh:(_Bool)arg1;
- (void)initWindowAndViewControllers;
- (id)invalidAlarmsDetected;
- (void)resetInvalidAlarmsLogging;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (void)saveState;
- (void)scheduleUserPreferencesCommit;
- (void)startedTest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

