//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol Clock
@property(readonly, nonatomic) int runMode;
- (void)start;
- (void)stop;
- (void)updateTime;

@optional
- (double)coarseUpdateInterval;
- (void)updateFlutter;
- (double)updateInterval;
- (void)updateTimeContinuously:(long long)arg1;
@end

