//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

@class UINavigationController;

@interface MobileTimerTabBarController : UITabBarController
{
    UINavigationController *_stopwatchNavController;
    UINavigationController *_timerNavController;
    UINavigationController *_alarmNavControllerSmall;
    UINavigationController *_alarmNavController;
    UINavigationController *_sleepAlarmNavController;
    UINavigationController *_worldClockNavControllerSmall;
    UINavigationController *_worldClockNavController;
}

- (void).cxx_destruct;
- (id)alarmViewController;
- (id)bedtimeViewController;
- (void)invalidateViewControllersWithTraitCollection:(id)arg1;
- (id)navigationControllerForHorizontalSizeClass:(long long)arg1 verticalSizeClass:(long long)arg2 atIndex:(int)arg3;
- (void)performActionForShortcutItem:(id)arg1;
- (void)populateShortcutItems;
- (id)stopwatchViewController;
- (unsigned long long)supportedInterfaceOrientations;
- (id)timerViewController;
- (id)topViewControllerForTab:(int)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (id)worldClockViewController;

@end

