//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class DigitalClockLabel, UIButton, UILabel, UISwitch;

@interface MTAlarmCollectionCell : UICollectionViewCell
{
    _Bool _editing;
    id <MTAlarmCollectionCellDelegate> _delegate;
    UIButton *_deleteButton;
    DigitalClockLabel *_timeLabel;
    UILabel *_nameLabel;
    UILabel *_repeatLabel;
    UILabel *_soundLabel;
    UISwitch *_enableSwitch;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MTAlarmCollectionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
- (void)deleteTapped:(id)arg1;
@property(nonatomic) _Bool editing; // @synthesize editing=_editing;
@property(readonly, nonatomic) struct CGRect editingPopoverSourceRect;
@property(retain, nonatomic) UISwitch *enableSwitch; // @synthesize enableSwitch=_enableSwitch;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)refreshUI:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UILabel *repeatLabel; // @synthesize repeatLabel=_repeatLabel;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UILabel *soundLabel; // @synthesize soundLabel=_soundLabel;
@property(retain, nonatomic) DigitalClockLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)setupConstraints;
- (void)toggleEnabled:(id)arg1;

@end

