//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface MTAnalogStopwatchHandView : UIView
{
    _Bool _hasTail;
    double _angle;
    double _width;
    UIColor *_color;
    unsigned long long _anchorStyle;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long anchorStyle; // @synthesize anchorStyle=_anchorStyle;
@property(nonatomic) double angle; // @synthesize angle=_angle;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) _Bool hasTail; // @synthesize hasTail=_hasTail;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double width; // @synthesize width=_width;

@end

