//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface MTCircleButton : UIButton
{
    unsigned long long _buttonCircleSize;
}

@property(nonatomic) unsigned long long buttonCircleSize; // @synthesize buttonCircleSize=_buttonCircleSize;
- (id)initWithFrame:(struct CGRect)arg1;
- (double)preferredHorizontalMargin;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

