//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UISlider;

@interface MTEditAlarmVolumeCell : UITableViewCell
{
    id <MTAlarmSoundInfoProvider> _alarm;
    id <MTEditAlarmVolumeCellDelegate> _delegate;
    UILabel *_titleLabel;
    UISlider *_volumeSlider;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <MTAlarmSoundInfoProvider> alarm; // @synthesize alarm=_alarm;
@property(nonatomic) float alarmVolume;
- (void)buildTitleLabel;
- (void)buildVolumeSlider;
- (void)commonInit;
@property __weak id <MTEditAlarmVolumeCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)drawDebugFrames;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain) UISlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
- (void)soundVolumeChanged:(id)arg1;
- (void)updateStyling;

@end

