//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MTSleepAlarm, MTSleepAlarmRepeatControl;

@interface MTSleepAlarmOptionsRecurrenceCell : UITableViewCell
{
    MTSleepAlarm *_alarm;
    id <MTSleepAlarmOptionsCellDelegate> _delegate;
    MTSleepAlarmRepeatControl *_recurrenceControl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MTSleepAlarm *alarm; // @synthesize alarm=_alarm;
- (void)buildRecurrenceControl;
@property(nonatomic) __weak id <MTSleepAlarmOptionsCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) MTSleepAlarmRepeatControl *recurrenceControl; // @synthesize recurrenceControl=_recurrenceControl;
- (void)recurrenceControlChanged:(id)arg1;
- (void)updateRecurrenceControl;

@end

