//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFastEnumeration.h"

@class NSDate, NSMutableSet;

@interface MTSleepAlarmGraphColumnData : NSObject <NSFastEnumeration>
{
    NSMutableSet *_intervals;
}

- (void).cxx_destruct;
- (void)addInterval:(id)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
@property(readonly, nonatomic) NSDate *endDate;
- (id)init;
@property(readonly, nonatomic) long long intervalCount;
@property(retain, nonatomic) NSMutableSet *intervals; // @synthesize intervals=_intervals;
- (id)orderedIntervals;
@property(readonly, nonatomic) NSDate *startDate;

@end

