//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray;

@interface MTSleepAlarmRepeatControl : UIControl
{
    long long _repeatSchedule;
    NSArray *_buttons;
    NSArray *_backgroundImages;
}

- (void).cxx_destruct;
- (void)_updateSelectedDays;
@property(retain, nonatomic) NSArray *backgroundImages; // @synthesize backgroundImages=_backgroundImages;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long repeatSchedule; // @synthesize repeatSchedule=_repeatSchedule;
- (void)setupConstraints;
- (void)toggleRepeats:(id)arg1;

@end

