//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MTSleepAlarm, NSLayoutConstraint, NSString, UIImageView, UILabel, UITableView;

@interface MTSleepAlarmReminderViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    id <MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
    MTSleepAlarm *_sleepAlarm;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UITableView *_tableView;
    NSLayoutConstraint *_titleBaselineConstraint;
    NSLayoutConstraint *_iconTitleConstraint;
}

- (void).cxx_destruct;
- (void)handleContentSizeChange:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *iconTitleConstraint; // @synthesize iconTitleConstraint=_iconTitleConstraint;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)loadView;
- (void)next:(id)arg1;
@property(nonatomic) __weak id <MTSleepAlarmOnboardingDelegate> onboardingDelegate; // @synthesize onboardingDelegate=_onboardingDelegate;
- (id)reminderMinutesForCellAtIndexPath:(id)arg1;
@property(retain, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSLayoutConstraint *titleBaselineConstraint; // @synthesize titleBaselineConstraint=_titleBaselineConstraint;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setupConstraints;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)titleForCellAtIndexPath:(id)arg1;
- (void)updateTitleBaselineConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

