//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSLayoutConstraint, UILabel, UISwitch, UIView;

@interface MTSleepAlarmSwitchView : UIControl
{
    UILabel *_enableLabel;
    UILabel *_repeatLabel;
    UISwitch *_enableSwitch;
    UIView *_keylineView;
    NSLayoutConstraint *_enableLabelLeadingConstraint;
    NSLayoutConstraint *_repeatLabelLeadingConstraint;
    NSLayoutConstraint *_switchTrailingConstraint;
    NSLayoutConstraint *_keylineLeadingConstraint;
    NSLayoutConstraint *_keylineTrailingConstraint;
    struct UIEdgeInsets _contentInset;
    struct UIEdgeInsets _separatorInset;
}

- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(retain, nonatomic) UILabel *enableLabel; // @synthesize enableLabel=_enableLabel;
@property(retain, nonatomic) NSLayoutConstraint *enableLabelLeadingConstraint; // @synthesize enableLabelLeadingConstraint=_enableLabelLeadingConstraint;
@property(retain, nonatomic) UISwitch *enableSwitch; // @synthesize enableSwitch=_enableSwitch;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isOn) _Bool on;
@property(retain, nonatomic) NSLayoutConstraint *keylineLeadingConstraint; // @synthesize keylineLeadingConstraint=_keylineLeadingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *keylineTrailingConstraint; // @synthesize keylineTrailingConstraint=_keylineTrailingConstraint;
@property(retain, nonatomic) UIView *keylineView; // @synthesize keylineView=_keylineView;
@property(retain, nonatomic) UILabel *repeatLabel; // @synthesize repeatLabel=_repeatLabel;
@property(retain, nonatomic) NSLayoutConstraint *repeatLabelLeadingConstraint; // @synthesize repeatLabelLeadingConstraint=_repeatLabelLeadingConstraint;
@property(nonatomic) struct UIEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
@property(retain, nonatomic) NSLayoutConstraint *switchTrailingConstraint; // @synthesize switchTrailingConstraint=_switchTrailingConstraint;
- (void)setupConstraints;
- (void)switchToggled:(id)arg1;
- (void)updateConstraints;
- (void)updateRepeatLabelForSchedule:(long long)arg1;

@end

