//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class DigitalClockLabel, MTSleepAlarm, MTSleepAlarmGraphView, NSArray, UIButton, UIFont, UILabel;

@interface MTSleepAlarmTimeInBedView : UIView
{
    UILabel *_titleLabel;
    DigitalClockLabel *_bedtimeLabel;
    DigitalClockLabel *_wakeLabel;
    MTSleepAlarmGraphView *_graphView;
    UIButton *_moreHistoryButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) DigitalClockLabel *bedtimeLabel; // @synthesize bedtimeLabel=_bedtimeLabel;
@property(retain, nonatomic) MTSleepAlarmGraphView *graphView; // @synthesize graphView=_graphView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIButton *moreHistoryButton; // @synthesize moreHistoryButton=_moreHistoryButton;
- (void)moreHistoryButtonPressed:(id)arg1;
@property(copy, nonatomic) MTSleepAlarm *sleepAlarm;
@property(retain, nonatomic) NSArray *sleepData;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) DigitalClockLabel *wakeLabel; // @synthesize wakeLabel=_wakeLabel;
- (void)setupConstraints;
@property(readonly, nonatomic) UIFont *titleFont;
- (id)viewForFirstBaselineLayout;
- (id)viewForLastBaselineLayout;

@end

