//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MTEditAlarmVolumeCellDelegate.h"
#import "MTSleepAlarmOptionsCellDelegate.h"
#import "TKTonePickerViewControllerDelegate.h"
#import "TKVibrationPickerViewControllerDelegate.h"

@class MTSleepAlarm, NSString, TKTonePickerViewController, TLAlert;

@interface MTSleepAlarmOptionsController : UITableViewController <MTSleepAlarmOptionsCellDelegate, MTEditAlarmVolumeCellDelegate, TKTonePickerViewControllerDelegate, TKVibrationPickerViewControllerDelegate>
{
    MTSleepAlarm *_sleepAlarm;
    id <MTSleepAlarmOptionsControllerDelegate> _optionsDelegate;
    MTSleepAlarm *_sourceSleepAlarm;
    TKTonePickerViewController *_tonePickerViewController;
    TLAlert *_previewAlert;
}

- (void).cxx_destruct;
- (id)bedtimeReminderCellForTableView:(id)arg1;
- (void)cancel:(id)arg1;
- (void)cancelEditing;
- (void)cell:(id)arg1 didModifyAlarm:(id)arg2;
- (void)cellDidEditAlarmVolume:(id)arg1;
- (void)didFinishPlayingAlarmToneForPreviewAlert:(id)arg1;
- (void)done:(id)arg1;
- (void)finishEditing;
- (void)handleSuspend;
- (id)initWithSleepAlarm:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) __weak id <MTSleepAlarmOptionsControllerDelegate> optionsDelegate; // @synthesize optionsDelegate=_optionsDelegate;
- (void)playAlarmTone;
@property(retain, nonatomic) TLAlert *previewAlert; // @synthesize previewAlert=_previewAlert;
- (id)recurrenceScheduleCellForTableView:(id)arg1;
@property(copy, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(copy, nonatomic) MTSleepAlarm *sourceSleepAlarm; // @synthesize sourceSleepAlarm=_sourceSleepAlarm;
@property(retain, nonatomic) TKTonePickerViewController *tonePickerViewController; // @synthesize tonePickerViewController=_tonePickerViewController;
- (void)showReminderIntervalPickerForCell:(id)arg1;
- (void)showTonePicker;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tonePickerCellForTableView:(id)arg1;
- (id)tonePickerController;
- (void)tonePickerViewController:(id)arg1 didDismissVibrationPickerViewController:(id)arg2;
- (void)tonePickerViewController:(id)arg1 selectedToneWithIdentifier:(id)arg2;
- (void)tonePickerViewController:(id)arg1 willPresentVibrationPickerViewController:(id)arg2;
- (void)updateDoneButtonEnabled;
- (void)vibrationPickerViewController:(id)arg1 selectedVibrationWithIdentifier:(id)arg2;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)volumeSliderCellForTableView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

