//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel, UIScrollView;

@interface MTSleepAlarmWelcomeViewController : UIViewController
{
    id <MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_getStartedButton;
    NSLayoutConstraint *_iconTitleConstraint;
    NSLayoutConstraint *_titleMessageConstraint;
}

- (void).cxx_destruct;
- (void)getStarted:(id)arg1;
@property(retain, nonatomic) UIButton *getStartedButton; // @synthesize getStartedButton=_getStartedButton;
- (void)handleContentSizeChange:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *iconTitleConstraint; // @synthesize iconTitleConstraint=_iconTitleConstraint;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)init;
- (void)loadView;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak id <MTSleepAlarmOnboardingDelegate> onboardingDelegate; // @synthesize onboardingDelegate=_onboardingDelegate;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSLayoutConstraint *titleMessageConstraint; // @synthesize titleMessageConstraint=_titleMessageConstraint;
- (void)setupConstraints;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end

