//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MTSleepAlarm, NSLayoutConstraint, UIDatePicker, UIImageView, UILabel;

@interface MTSleepAlarmWakeTimeViewController : UIViewController
{
    id <MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
    MTSleepAlarm *_sleepAlarm;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UIDatePicker *_timePicker;
    NSLayoutConstraint *_titleBaselineConstraint;
    NSLayoutConstraint *_iconTitleConstraint;
}

- (void).cxx_destruct;
- (void)cancel:(id)arg1;
- (void)handleContentSizeChange:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *iconTitleConstraint; // @synthesize iconTitleConstraint=_iconTitleConstraint;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)loadView;
- (void)next:(id)arg1;
@property(nonatomic) __weak id <MTSleepAlarmOnboardingDelegate> onboardingDelegate; // @synthesize onboardingDelegate=_onboardingDelegate;
@property(retain, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) UIDatePicker *timePicker; // @synthesize timePicker=_timePicker;
@property(retain, nonatomic) NSLayoutConstraint *titleBaselineConstraint; // @synthesize titleBaselineConstraint=_titleBaselineConstraint;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setupConstraints;
- (void)updateTitleBaselineConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

