//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MTSleepAlarm, NSArray, NSCalendar, NSDate;

@interface MTSleepAlarmGraphData : NSObject
{
    MTSleepAlarm *_sleepAlarm;
    NSArray *_allColumnData;
    NSCalendar *_calendar;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *allColumnData; // @synthesize allColumnData=_allColumnData;
@property(readonly, nonatomic) double bedtimeOriginY;
@property(retain, nonatomic) NSCalendar *calendar; // @synthesize calendar=_calendar;
@property(readonly, nonatomic) long long columnCount;
@property(readonly, nonatomic) NSDate *earliestStartOnFirstDay;
@property(readonly, nonatomic) double height;
- (id)initWithSleepData:(id)arg1 sleepAlarm:(id)arg2;
@property(readonly, nonatomic) NSDate *latestEndOnFirstDay;
- (id)objectAtIndexedSubscript:(long long)arg1;
@property(retain, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
- (id)sleepAlarmIntervalForDay:(long long)arg1;
@property(readonly, nonatomic) double wakeTimeOriginY;

@end

