//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MTSleepAlarmOptionsControllerDelegate.h"

@class HKHealthStore, HKObserverQuery, MTSleepAlarm, MTSleepAlarmClockView, MTSleepAlarmSwitchView, MTSleepAlarmTimeInBedView, MTSleepAlarmTimeView, NSArray, NSString, NSUserActivity, UIScrollView, UIView;

@interface MTSleepAlarmViewController : UIViewController <MTSleepAlarmOptionsControllerDelegate>
{
    NSUserActivity *_userActivity;
    _Bool _contentViewLoaded;
    MTSleepAlarm *_sleepAlarm;
    UIScrollView *_scrollView;
    UIView *_contentView;
    MTSleepAlarmSwitchView *_switchView;
    MTSleepAlarmTimeView *_sleepTimeView;
    MTSleepAlarmTimeView *_wakeTimeView;
    MTSleepAlarmClockView *_circleView;
    MTSleepAlarmTimeInBedView *_timeInBedView;
    HKHealthStore *_healthStore;
    HKObserverQuery *_healthObserver;
    NSArray *_contentViewConstraints;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MTSleepAlarmClockView *circleView; // @synthesize circleView=_circleView;
- (void)circleViewDidEndEditing:(id)arg1;
- (void)circleViewEdited:(id)arg1;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSArray *contentViewConstraints; // @synthesize contentViewConstraints=_contentViewConstraints;
@property(nonatomic) _Bool contentViewLoaded; // @synthesize contentViewLoaded=_contentViewLoaded;
- (void)dealloc;
- (void)enableSwitchToggled:(id)arg1;
@property(retain, nonatomic) HKObserverQuery *healthObserver; // @synthesize healthObserver=_healthObserver;
@property(retain, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
- (id)init;
- (id)initWithSleepAlarm:(id)arg1;
- (void)loadSleepData;
- (void)loadView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)setEditingEnabled:(_Bool)arg1;
@property(copy, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) MTSleepAlarmTimeView *sleepTimeView; // @synthesize sleepTimeView=_sleepTimeView;
@property(retain, nonatomic) MTSleepAlarmSwitchView *switchView; // @synthesize switchView=_switchView;
@property(retain, nonatomic) MTSleepAlarmTimeInBedView *timeInBedView; // @synthesize timeInBedView=_timeInBedView;
@property(retain, nonatomic) MTSleepAlarmTimeView *wakeTimeView; // @synthesize wakeTimeView=_wakeTimeView;
- (void)setupCompactContentViewConstraints;
- (void)setupConstraints;
- (void)setupContentViewConstraints;
- (void)setupRegularLandscapeContentViewConstraints;
- (void)setupRegularPortraitContentViewConstraints;
- (void)showOptions:(id)arg1;
- (void)sleepAlarmOptionsController:(id)arg1 saveOptionsWithSleepAlarm:(id)arg2;
- (void)sleepAlarmOptionsControllerDidCancel:(id)arg1;
- (void)startListeningForHealthKitChanges;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

