//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MTSleepAlarm, MTSleepAlarmGraphData, NSArray, NSLayoutConstraint, UILayoutGuide, UITapGestureRecognizer;

@interface MTSleepAlarmGraphView : UIView
{
    UILayoutGuide *_axesLayoutGuide;
    MTSleepAlarm *_sleepAlarm;
    NSArray *_sleepData;
    MTSleepAlarmGraphData *_graphData;
    NSLayoutConstraint *_topAxisConstraint;
    NSLayoutConstraint *_bottomAxisConstraint;
    NSArray *_dayLabels;
    NSArray *_dayCenterXConstraints;
    NSLayoutConstraint *_labelBaselineConstraint;
    UITapGestureRecognizer *_tapRecognizer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILayoutGuide *axesLayoutGuide; // @synthesize axesLayoutGuide=_axesLayoutGuide;
- (double)barSpacing;
@property(retain, nonatomic) NSLayoutConstraint *bottomAxisConstraint; // @synthesize bottomAxisConstraint=_bottomAxisConstraint;
@property(retain, nonatomic) NSArray *dayCenterXConstraints; // @synthesize dayCenterXConstraints=_dayCenterXConstraints;
@property(retain, nonatomic) NSArray *dayLabels; // @synthesize dayLabels=_dayLabels;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) MTSleepAlarmGraphData *graphData; // @synthesize graphData=_graphData;
- (void)graphTapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSLayoutConstraint *labelBaselineConstraint; // @synthesize labelBaselineConstraint=_labelBaselineConstraint;
- (void)layoutSubviews;
- (void)processSleepData;
@property(copy, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) NSArray *sleepData; // @synthesize sleepData=_sleepData;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *topAxisConstraint; // @synthesize topAxisConstraint=_topAxisConstraint;
- (void)setupConstraints;
- (id)viewForLastBaselineLayout;

@end

