//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MTSleepAlarm, MTSleepAlarmRepeatControl, NSLayoutConstraint, UIImageView, UILabel;

@interface MTSleepAlarmScheduleViewController : UIViewController
{
    id <MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
    MTSleepAlarm *_sleepAlarm;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_explanatoryLabel;
    MTSleepAlarmRepeatControl *_repeatControl;
    UILabel *_repeatLabel;
    NSLayoutConstraint *_titleBaselineConstraint;
    NSLayoutConstraint *_iconTitleConstraint;
    NSLayoutConstraint *_titleMessageConstraint;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *explanatoryLabel; // @synthesize explanatoryLabel=_explanatoryLabel;
- (void)handleContentSizeChange:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *iconTitleConstraint; // @synthesize iconTitleConstraint=_iconTitleConstraint;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)loadView;
- (void)next:(id)arg1;
@property(nonatomic) __weak id <MTSleepAlarmOnboardingDelegate> onboardingDelegate; // @synthesize onboardingDelegate=_onboardingDelegate;
@property(retain, nonatomic) MTSleepAlarmRepeatControl *repeatControl; // @synthesize repeatControl=_repeatControl;
- (void)repeatControlChanged:(id)arg1;
@property(retain, nonatomic) UILabel *repeatLabel; // @synthesize repeatLabel=_repeatLabel;
@property(retain, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) NSLayoutConstraint *titleBaselineConstraint; // @synthesize titleBaselineConstraint=_titleBaselineConstraint;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSLayoutConstraint *titleMessageConstraint; // @synthesize titleMessageConstraint=_titleMessageConstraint;
- (void)setupConstraints;
- (void)updateTitleBaselineConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

