//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class DigitalClockLabel, NSLayoutConstraint, UIImage, UIImageView, UILabel;

@interface MTSleepAlarmTimeView : UIView
{
    _Bool _enabled;
    unsigned long long _style;
    UIImageView *_iconView;
    UILabel *_eventLabel;
    DigitalClockLabel *_timeLabel;
    NSLayoutConstraint *_eventBaselineConstraint;
    NSLayoutConstraint *_timeBaselineConstraint;
    unsigned long long _event;
    UIImage *_untintedImage;
}

- (void).cxx_destruct;
- (void)_updateColors;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) unsigned long long event; // @synthesize event=_event;
@property(retain, nonatomic) NSLayoutConstraint *eventBaselineConstraint; // @synthesize eventBaselineConstraint=_eventBaselineConstraint;
@property(retain, nonatomic) UILabel *eventLabel; // @synthesize eventLabel=_eventLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (id)initWithTimeEvent:(unsigned long long)arg1;
- (void)setHour:(unsigned long long)arg1 minute:(unsigned long long)arg2;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) NSLayoutConstraint *timeBaselineConstraint; // @synthesize timeBaselineConstraint=_timeBaselineConstraint;
@property(retain, nonatomic) DigitalClockLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImage *untintedImage; // @synthesize untintedImage=_untintedImage;
- (void)setupConstraints;
- (void)updateConstraints;
- (id)viewForLastBaselineLayout;

@end

