//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MTSleepAlarm, UILabel;

@interface MTSleepAlarmOptionsBedtimeReminderCell : UITableViewCell
{
    MTSleepAlarm *_alarm;
}

+ (id)timeFormatter;
- (void).cxx_destruct;
@property(retain, nonatomic) MTSleepAlarm *alarm; // @synthesize alarm=_alarm;
- (id)bedtimeReminderTimeString;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)reload;
@property(readonly) UILabel *reminderIntervalLabel;

@end

