//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class MTSleepAlarm, NSDateComponentsFormatter, NSLayoutConstraint, NSString, UIImageView, UILabel, UIPickerView;

@interface MTSleepAlarmHoursOfSleepViewController : UIViewController <UIPickerViewDataSource, UIPickerViewDelegate>
{
    id <MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
    MTSleepAlarm *_sleepAlarm;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_explanatoryLabel;
    UIPickerView *_hoursPicker;
    NSDateComponentsFormatter *_formatter;
    NSLayoutConstraint *_titleBaselineConstraint;
    NSLayoutConstraint *_iconTitleConstraint;
    NSLayoutConstraint *_titleMessageConstraint;
}

- (void).cxx_destruct;
- (void)applySleepTimeFromPicker;
- (void)cancel:(id)arg1;
@property(retain, nonatomic) UILabel *explanatoryLabel; // @synthesize explanatoryLabel=_explanatoryLabel;
@property(retain, nonatomic) NSDateComponentsFormatter *formatter; // @synthesize formatter=_formatter;
- (void)handleContentSizeChange:(id)arg1;
@property(retain, nonatomic) UIPickerView *hoursPicker; // @synthesize hoursPicker=_hoursPicker;
@property(retain, nonatomic) NSLayoutConstraint *iconTitleConstraint; // @synthesize iconTitleConstraint=_iconTitleConstraint;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)loadView;
- (void)next:(id)arg1;
- (long long)numberOfComponentsInPickerView:(id)arg1;
@property(nonatomic) __weak id <MTSleepAlarmOnboardingDelegate> onboardingDelegate; // @synthesize onboardingDelegate=_onboardingDelegate;
- (id)pickerView:(id)arg1 attributedTitleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
@property(retain, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) NSLayoutConstraint *titleBaselineConstraint; // @synthesize titleBaselineConstraint=_titleBaselineConstraint;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSLayoutConstraint *titleMessageConstraint; // @synthesize titleMessageConstraint=_titleMessageConstraint;
- (void)setupConstraints;
- (void)updateTitleBaselineConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

