//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MTSleepAlarm, NSLayoutConstraint, UIImageView, UILabel, UIScrollView;

@interface MTSleepAlarmOnboardingCompleteViewController : UIViewController
{
    id <MTSleepAlarmOnboardingDelegate> _onboardingDelegate;
    MTSleepAlarm *_sleepAlarm;
    UIScrollView *_scrollView;
    UIImageView *_glyphImageView;
    UIImageView *_graphImageView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UILabel *_footerLabel;
    NSLayoutConstraint *_titleBaselineConstraint;
    NSLayoutConstraint *_iconTitleConstraint;
    NSLayoutConstraint *_titleMessageConstraint;
}

- (void).cxx_destruct;
- (void)done:(id)arg1;
@property(retain, nonatomic) UILabel *footerLabel; // @synthesize footerLabel=_footerLabel;
@property(retain, nonatomic) UIImageView *glyphImageView; // @synthesize glyphImageView=_glyphImageView;
@property(retain, nonatomic) UIImageView *graphImageView; // @synthesize graphImageView=_graphImageView;
- (void)handleContentSizeChange:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *iconTitleConstraint; // @synthesize iconTitleConstraint=_iconTitleConstraint;
- (id)init;
- (void)loadView;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) __weak id <MTSleepAlarmOnboardingDelegate> onboardingDelegate; // @synthesize onboardingDelegate=_onboardingDelegate;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) MTSleepAlarm *sleepAlarm; // @synthesize sleepAlarm=_sleepAlarm;
@property(retain, nonatomic) NSLayoutConstraint *titleBaselineConstraint; // @synthesize titleBaselineConstraint=_titleBaselineConstraint;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSLayoutConstraint *titleMessageConstraint; // @synthesize titleMessageConstraint=_titleMessageConstraint;
- (void)setupConstraints;
- (void)updateTitleBaselineConstraint;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

