//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface MTStopwatchLapTableHeaderView : UIView
{
    UILabel *_lapNumberLabel;
    UILabel *_splitLabel;
    UILabel *_totalLabel;
    UIView *_bottomKeylineView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bottomKeylineView; // @synthesize bottomKeylineView=_bottomKeylineView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *lapNumberLabel; // @synthesize lapNumberLabel=_lapNumberLabel;
@property(retain, nonatomic) UILabel *splitLabel; // @synthesize splitLabel=_splitLabel;
@property(retain, nonatomic) UILabel *totalLabel; // @synthesize totalLabel=_totalLabel;
- (void)setupConstraints;

@end

