//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@class UIView;

@interface MTStopwatchTableView : UITableView
{
    UIView *_topKeylineView;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) UIView *topKeylineView; // @synthesize topKeylineView=_topKeylineView;

@end

