//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MTCircleButton;

@interface MTTimerButtonsController : NSObject
{
    int _state;
    id <TimerControlsTarget> _target;
    MTCircleButton *_startStopButton;
    MTCircleButton *_cancelButton;
    unsigned long long _buttonSize;
}

- (void).cxx_destruct;
- (void)_cancelButtonTapped:(id)arg1;
- (void)_startStopButtonTapped:(id)arg1;
@property(nonatomic) unsigned long long buttonSize; // @synthesize buttonSize=_buttonSize;
@property(readonly, nonatomic) MTCircleButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (id)initWithTarget:(id)arg1;
@property(nonatomic) int state; // @synthesize state=_state;
@property(readonly, nonatomic) MTCircleButton *startStopButton; // @synthesize startStopButton=_startStopButton;
@property(readonly, nonatomic) __weak id <TimerControlsTarget> target; // @synthesize target=_target;

@end

