//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TimerTimeView, UIDatePicker, UIView;

@interface MTTimerPickerCell : UITableViewCell
{
    UIView *_pickerBackgroundView;
    int _state;
    UIDatePicker *_picker;
    TimerTimeView *_timeView;
}

- (void).cxx_destruct;
- (id)initWithPicker:(id)arg1 timeView:(id)arg2 reuseIdentifier:(id)arg3;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIDatePicker *picker; // @synthesize picker=_picker;
@property(nonatomic) int state; // @synthesize state=_state;
- (void)setState:(int)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) TimerTimeView *timeView; // @synthesize timeView=_timeView;

@end

