//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString;

@interface MTTonePickerCell : UITableViewCell
{
    id <MTAlarmSoundInfoProvider> _alarmProvider;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MTAlarmSoundInfoProvider> alarmProvider; // @synthesize alarmProvider=_alarmProvider;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)reload;
@property(copy, nonatomic) NSString *title;

@end

