//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "Clock.h"

@class AnalogClockView, NSDateFormatter, UILabel, WorldClockCity;

@interface MTWorldClockView : UIView <Clock>
{
    WorldClockCity *_city;
    AnalogClockView *_analogClock;
    UILabel *_cityNameLabel;
    UILabel *_timeZoneOffsetLabel;
    UILabel *_sunriseLabel;
    UILabel *_sunsetLabel;
    long long _minute;
    NSDateFormatter *_timeFormatter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AnalogClockView *analogClock; // @synthesize analogClock=_analogClock;
@property(retain, nonatomic) WorldClockCity *city; // @synthesize city=_city;
@property(retain, nonatomic) UILabel *cityNameLabel; // @synthesize cityNameLabel=_cityNameLabel;
- (double)coarseUpdateInterval;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long minute; // @synthesize minute=_minute;
@property(readonly, nonatomic) int runMode;
@property(retain, nonatomic) UILabel *sunriseLabel; // @synthesize sunriseLabel=_sunriseLabel;
@property(retain, nonatomic) UILabel *sunsetLabel; // @synthesize sunsetLabel=_sunsetLabel;
@property(retain, nonatomic) NSDateFormatter *timeFormatter; // @synthesize timeFormatter=_timeFormatter;
@property(retain, nonatomic) UILabel *timeZoneOffsetLabel; // @synthesize timeZoneOffsetLabel=_timeZoneOffsetLabel;
- (void)setupConstraints;
- (void)start;
- (void)stop;
- (void)updateDetails;
- (void)updateFlutter;
- (double)updateInterval;
- (void)updateTime;
- (void)updateTimeContinuously:(long long)arg1;

@end

