//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

#import "UICollectionViewDelegateFlowLayout.h"
#import "WorldClockCollectionCellDelegate.h"

@class MTWorldClockGridLayout, NSString, WorldClockCollectionCell;

@interface MTWorldClockCollectionViewController : UICollectionViewController <UICollectionViewDelegateFlowLayout, WorldClockCollectionCellDelegate>
{
    double _cellHeight;
    id <MTWorldClockCollectionViewDelegate> _delegate;
    WorldClockCollectionCell *_sizingCell;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
@property(nonatomic) __weak id <MTWorldClockCollectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteCell:(id)arg1;
- (void)handleContentSizeChange;
- (void)handleScrollEnd;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)removeCityAtIndexPath:(id)arg1;
- (void)scrollToPageContainingIndexPath:(id)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)setEditing:(_Bool)arg1;
@property(retain, nonatomic) WorldClockCollectionCell *sizingCell; // @synthesize sizingCell=_sizingCell;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) MTWorldClockGridLayout *collectionViewLayout; // @dynamic collectionViewLayout;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

