//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MTStopwatchPagingViewControllerDelegate.h"
#import "StateManagement.h"
#import "StopWatchControlsTarget.h"

@class CADisplayLink, MTAnalogStopwatchView, MTStopwatchController, MTStopwatchLapTableHeaderView, MTStopwatchLapTableViewController, MTStopwatchPagingViewController, MTTimeView, NSArray, NSDate, NSMutableArray, NSString, NSTimer, NSUserActivity, UIImageView, UIPageControl, UIView;

@interface StopWatchViewController : UIViewController <MTStopwatchPagingViewControllerDelegate, StateManagement, StopWatchControlsTarget>
{
    CADisplayLink *_displayLink;
    NSDate *_startTime;
    double _offset;
    double _currentInterval;
    double _previousLapsTotalInterval;
    NSMutableArray *_laps;
    _Bool _isTimerRunning;
    NSTimer *_restoreIdleTimerTimer;
    int _mode;
    NSUserActivity *_userActivity;
    MTStopwatchController *_stopwatchController;
    MTStopwatchLapTableViewController *_lapTableController;
    MTStopwatchLapTableHeaderView *_tableHeaderView;
    UIImageView *_lapButtonOccludingView;
    UIImageView *_startButtonOccludingView;
    MTStopwatchPagingViewController *_pagingViewController;
    UIPageControl *_pageControl;
    UIView *_analogStopwatchContainer;
    MTAnalogStopwatchView *_analogStopwatch;
    UIView *_digitalStopwatchContainer;
    MTTimeView *_timeView;
    NSArray *_constraints;
    struct CGSize _latestLayoutSize;
}

- (void).cxx_destruct;
- (void)_addLap:(double)arg1;
- (void)_clearAllLaps;
- (void)_restoreIdleTimer;
- (void)_startTimer;
- (void)_stopTimer;
- (void)_tick:(id)arg1;
- (double)_timeAdjustedFor30fpsDisplay:(double)arg1;
@property(retain, nonatomic) MTAnalogStopwatchView *analogStopwatch; // @synthesize analogStopwatch=_analogStopwatch;
@property(retain, nonatomic) UIView *analogStopwatchContainer; // @synthesize analogStopwatchContainer=_analogStopwatchContainer;
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
- (void)dealloc;
- (id)defaultShortcutItem;
@property(retain, nonatomic) UIView *digitalStopwatchContainer; // @synthesize digitalStopwatchContainer=_digitalStopwatchContainer;
- (void)handleLocaleChange;
- (void)handleStartStopwatchShortcutAction;
- (void)handleStopStopwatchShortcutAction;
- (id)init;
@property(retain, nonatomic) UIImageView *lapButtonOccludingView; // @synthesize lapButtonOccludingView=_lapButtonOccludingView;
- (void)lapLapTimer;
@property(retain, nonatomic) MTStopwatchLapTableViewController *lapTableController; // @synthesize lapTableController=_lapTableController;
@property(nonatomic) struct CGSize latestLayoutSize; // @synthesize latestLayoutSize=_latestLayoutSize;
- (void)loadView;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) MTStopwatchPagingViewController *pagingViewController; // @synthesize pagingViewController=_pagingViewController;
- (void)pauseLapTimer;
- (_Bool)prefersStatusBarHidden;
- (void)reloadState;
- (void)resetLapTimer;
- (void)resumeLapTimer;
- (double)runningTotalForLap:(long long)arg1;
- (void)saveState;
- (void)setMode:(int)arg1;
@property(retain, nonatomic) UIImageView *startButtonOccludingView; // @synthesize startButtonOccludingView=_startButtonOccludingView;
@property(retain, nonatomic) MTStopwatchController *stopwatchController; // @synthesize stopwatchController=_stopwatchController;
@property(retain, nonatomic) MTStopwatchLapTableHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) MTTimeView *timeView; // @synthesize timeView=_timeView;
- (id)shortcutItemForCurrentState;
- (id)shortcutItemForMode:(int)arg1;
- (void)startLapTimer;
- (id)startStopwatchShortcutItemForMode:(int)arg1;
- (id)stopStopwatchShortcutItem;
- (void)stopwatchPagingViewController:(id)arg1 didPage:(unsigned long long)arg2;
- (Class)tableCellClass;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateShortcutItemForCurrentState;
- (void)updateTime;
- (void)updateTimeViewFont;
- (void)updateViewConstraints;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

