//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MTAddItemController.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIBarButtonItem, UITableView, UIView, _UIContentUnavailableView;

@interface TableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, MTAddItemController>
{
    UIView *_backgroundView;
    UITableView *_tableView;
    UIBarButtonItem *_addButton;
    _UIContentUnavailableView *_noItemsView;
}

- (void).cxx_destruct;
- (void)_layoutNoItemsLabel;
- (void)_numberOfItemsDidChangeAnimated:(_Bool)arg1;
@property(readonly, nonatomic) UIBarButtonItem *addButton; // @synthesize addButton=_addButton;
- (id)addViewController;
- (void)dismissAddViewController:(id)arg1;
- (id)init;
- (float)itemsTableRowHeight;
- (void)loadView;
- (id)noItemsText;
- (long long)numberOfItems;
- (void)reloadState;
- (void)saveScrollPoint;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)showAddView;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidUnload;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

