//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface TimeView : UIView
{
    double _timeValue;
    UILabel *_timeLabel;
    double _maxTimeLabelWidth;
}

+ (double)defaultHeight;
- (void).cxx_destruct;
- (void)configureBackground;
- (void)configureTimeLabel;
- (void)handleLocaleChange;
- (id)init;
- (void)layoutSubviews;
@property(nonatomic) double time;
- (void)setTimeLabelFrame:(struct CGRect)arg1;
- (_Bool)showSubseconds;
- (void)sizeLabelToFit;
@property(readonly, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;

@end

