//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ClockManagerNotificationObserver.h"
#import "StateManagement.h"
#import "TKTonePickerViewControllerDelegate.h"
#import "TimerControlsTarget.h"
#import "UINavigationControllerDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class NSString, NSTimer, NSUserActivity, TKTonePickerViewController, TimerControlsView;

@interface TimerViewController : UIViewController <TKTonePickerViewControllerDelegate, UINavigationControllerDelegate, StateManagement, TimerControlsTarget, UIPopoverPresentationControllerDelegate, ClockManagerNotificationObserver>
{
    TimerControlsView *_timerControlsView;
    TKTonePickerViewController *_tonePickerViewController;
    NSString *_soundIdentifier;
    NSTimer *_timer;
    double _time;
    _Bool _layoutForTraitChange;
    int _style;
    NSUserActivity *_userActivity;
}

- (void).cxx_destruct;
- (void)cancelTimer:(id)arg1;
- (void)confirmPickingSound;
- (void)dealloc;
- (id)defaultShortcutItem;
- (void)dismissSoundPicker;
- (void)handleEnterBackground;
- (void)handleStartTimerShortcutAction;
- (void)handleStopTimerShortcutAction;
- (id)init;
- (void)loadView;
- (void)localNotificationsDidChangeForClockManager:(id)arg1;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (void)pauseResumeTimer:(id)arg1;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)prepareUIForState:(int)arg1;
- (void)reloadState;
- (void)saveState;
- (void)setStyle:(int)arg1;
- (id)shortcutItemForCurrentState;
- (void)showSoundPicker:(id)arg1;
- (void)startTimer:(id)arg1;
- (id)startTimerShortcutItem;
- (void)startUpdatingTimerUI;
- (id)stopTimerShortcutItem;
- (void)stopUpdatingTimerUI;
- (void)timerTick:(id)arg1;
- (void)tonePickerViewController:(id)arg1 selectedToneWithIdentifier:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateSelectedSoundUI;
- (id)updateSelectedSoundUIForIdentifier:(id)arg1;
- (void)updateShortcutItemForCurrentState;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end
