//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AddClockViewControllerDelegate.h"
#import "MTAddItemController.h"
#import "MTWorldClockCollectionViewDelegate.h"
#import "StateManagement.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class MTWorldClockCollectionViewController, NSLayoutConstraint, NSString, NSUserActivity, UINavigationController, WorldClockMapView;

@interface WorldClockPadViewController : UIViewController <MTAddItemController, MTWorldClockCollectionViewDelegate, UIPopoverPresentationControllerDelegate, AddClockViewControllerDelegate, StateManagement, UIGestureRecognizerDelegate>
{
    UINavigationController *_addClockNavigationController;
    long long _addedClockIndex;
    _Bool _initializedCurrentPage;
    _Bool _prefersStatusBarHidden;
    long long _statusBarStyle;
    NSUserActivity *_userActivity;
    MTWorldClockCollectionViewController *_collectionViewController;
    WorldClockMapView *_mapView;
    NSLayoutConstraint *_mapHeightConstraint;
    NSLayoutConstraint *_collectionBottomConstraint;
}

- (void).cxx_destruct;
- (void)addClock:(id)arg1;
- (void)addClockViewController:(id)arg1 addCity:(id)arg2;
@property(retain, nonatomic) NSLayoutConstraint *collectionBottomConstraint; // @synthesize collectionBottomConstraint=_collectionBottomConstraint;
- (void)collectionView:(id)arg1 didRemoveCity:(id)arg2;
@property(retain, nonatomic) MTWorldClockCollectionViewController *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
- (void)dismissAddViewController:(id)arg1;
- (void)handleApplicationDidEnterBackground;
- (void)handleApplicationWillEnterForeground;
- (void)handleContentSizeChange:(id)arg1;
- (id)init;
- (void)loadView;
- (double)mapHeight;
@property(retain, nonatomic) NSLayoutConstraint *mapHeightConstraint; // @synthesize mapHeightConstraint=_mapHeightConstraint;
@property(retain, nonatomic) WorldClockMapView *mapView; // @synthesize mapView=_mapView;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)reloadState;
- (void)saveState;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setPrefersStatusBarHidden:(_Bool)arg1;
- (void)setStatusBarStyle:(long long)arg1;
- (void)setupConstraints;
- (_Bool)shouldShowAddView;
- (_Bool)shouldToggleEditView;
- (void)showAddView;
- (void)startUpdates;
- (void)stopUpdates;
- (unsigned long long)supportedInterfaceOrientations;
- (void)toggleEditView;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateClocksForSize:(struct CGSize)arg1 transitionCoordinator:(id)arg2;
- (void)updateViewConstraints;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

