//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "Clock.h"

@class NSDateFormatter, UIImageView, UILabel, WorldClockCity;

@interface WorldClockMapCityView : UIView <Clock>
{
    WorldClockCity *_city;
    UILabel *_timeLabel;
    UILabel *_nameLabel;
    NSDateFormatter *_timeFormatter;
    _Bool _doneFirstLayout;
    int _iconPlacement;
    UIImageView *_dotImageView;
}

+ (id)secondaryLabelFont;
- (void).cxx_destruct;
@property(readonly, nonatomic) WorldClockCity *city; // @synthesize city=_city;
- (struct CGRect)dotImageFrameForPlacement:(int)arg1;
@property(retain, nonatomic) UIImageView *dotImageView; // @synthesize dotImageView=_dotImageView;
- (void)handleLocaleChange;
- (struct CGPoint)hotspotOffset;
- (struct CGPoint)hotspotOffsetForPlacement:(int)arg1;
@property(nonatomic) int iconPlacement; // @synthesize iconPlacement=_iconPlacement;
- (id)initWithCity:(id)arg1;
- (id)labelViews;
- (void)layoutIfNeeded;
- (void)layoutSubviews;
@property(readonly, nonatomic) int runMode;
- (void)setCity:(id)arg1;
@property(copy, nonatomic) NSDateFormatter *timeFormatter; // @synthesize timeFormatter=_timeFormatter;
@property(nonatomic) double timeLabelWidth;
- (struct CGSize)sizeForIntersectionWithCityView:(id)arg1 atOrigin:(struct CGPoint)arg2 selfOrigin:(struct CGPoint)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)start;
- (void)stop;
- (void)updateTime;

@end

